gamma: 0.95   # Reward discount
learning_rate: 0.001
memory_size: 10000
epsilon: 0.8  # Exploration rate
epsilon_min: 0.05
epsilon_decay: 0.995
batch_size: 32
update_frequency: 50
replay_frequency: 10
alpha: 0.6    # Used during priority calculation
beta: 0.4  # Used during importance sampling
beta_increase: 0.001
beta_max: 1